// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB157VTUPPaH9n29IQmmCH-OTta2kNg4-I',
    appId: '1:640949829571:web:686e23ed41bd9a4ca84776',
    messagingSenderId: '640949829571',
    projectId: 'online-voting-app-2f05e',
    authDomain: 'online-voting-app-2f05e.firebaseapp.com',
    storageBucket: 'online-voting-app-2f05e.firebasestorage.app',
    measurementId: 'G-XV3M59S2WB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLRxND_6KgPuEjsmfNyZxQDgfjlVnj0fY',
    appId: '1:640949829571:android:c1d1b4d30f67e1f6a84776',
    messagingSenderId: '640949829571',
    projectId: 'online-voting-app-2f05e',
    storageBucket: 'online-voting-app-2f05e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVQasZspSTVJ5V4lIPetQSAnoWGEIIMxQ',
    appId: '1:640949829571:ios:7b453b32ab534533a84776',
    messagingSenderId: '640949829571',
    projectId: 'online-voting-app-2f05e',
    storageBucket: 'online-voting-app-2f05e.firebasestorage.app',
    iosBundleId: 'com.example.onlineVotingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCVQasZspSTVJ5V4lIPetQSAnoWGEIIMxQ',
    appId: '1:640949829571:ios:7b453b32ab534533a84776',
    messagingSenderId: '640949829571',
    projectId: 'online-voting-app-2f05e',
    storageBucket: 'online-voting-app-2f05e.firebasestorage.app',
    iosBundleId: 'com.example.onlineVotingApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB157VTUPPaH9n29IQmmCH-OTta2kNg4-I',
    appId: '1:640949829571:web:ac41ef0d7835783da84776',
    messagingSenderId: '640949829571',
    projectId: 'online-voting-app-2f05e',
    authDomain: 'online-voting-app-2f05e.firebaseapp.com',
    storageBucket: 'online-voting-app-2f05e.firebasestorage.app',
    measurementId: 'G-CG5M9NHQC0',
  );
}
